### ISSUE TITLE
Shared DBusConnection between KDEWalletKeychainAccess and SecretServiceKeychainAccess leads to infinite loop in SecretServiceKeychainAccess

### ISSUE THREAD

**Issue by SailReal** [cryptomator/integrations-linux#12]
Since the dependency bump of https://github.com/cryptomator/integrations-linux/commit/0e13a3fb552ac35e5d29bc12b5513a1a9a0226f2, Cryptomator isn't able to start up when `KDEWalletKeychainAccess` and `SecretServiceKeychainAccess` is used as `KeychainAccessProvider`. The problem is that in `KDEWalletKeychainAccess` we connect to a shared connection using `getConnection(DBusConnection.DBusBusType.SESSION)`. This connection gets never closed which in return leads to problems in the [SecretServiceKeychainAccess.isLocked](https://github.com/cryptomator/integrations-linux/blob/0e13a3fb552ac35e5d29bc12b5513a1a9a0226f2/src/main/java/org/cryptomator/linux/keychain/SecretServiceKeychainAccess.java#L27-L34) as it tries to close the connection but never succeeds because of the still active and shared connecting of `KDEWalletKeychainAccess` and the active waiting until all connections are closed in [SimpleCollection.disconnectSynchronized](https://github.com/swiesend/secret-service/blob/71bbddcc833a6712e0d8c14e326678abdb798456/src/main/java/org/freedesktop/secret/simple/SimpleCollection.java#L203-L219)

 `SecretServiceKeychainAccess` and `KDEWalletKeychainAccess` should not share a connection.

Some further information from https://github.com/cryptomator/cryptomator/issues/1815#issuecomment-929399558

> While startup in [SecretServiceKeychainAccess#isLocked](https://github.com/cryptomator/integrations-linux/blob/0e13a3fb552ac35e5d29bc12b5513a1a9a0226f2/src/main/java/org/cryptomator/linux/keychain/SecretServiceKeychainAccess.java#L27-L34) we check if the `keyring` is locked. As this `keyring` is instantiated in an try-with statement, it will be closed after leaving the scope. 
> 
> Close calls [SimpleCollection#disconnect](https://github.com/swiesend/secret-service/blob/71bbddcc833a6712e0d8c14e326678abdb798456/src/main/java/org/freedesktop/secret/simple/SimpleCollection.java#L401) which calls [SimpleCollection#disconnectSynchronized](https://github.com/swiesend/secret-service/blob/71bbddcc833a6712e0d8c14e326678abdb798456/src/main/java/org/freedesktop/secret/simple/SimpleCollection.java#L203). After calling `connection.close` we wait until it is actually closed in a while-`connection.isConnected()`-loop.  `connection.close` calls [DBusConnection#disconnect](https://github.com/hypfvieh/dbus-java/blob/036ab5d6e5a84be8dce25454ecc04ae32af2916d/dbus-java/src/main/java/org/freedesktop/dbus/connections/impl/DBusConnection.java#L977-L978) and there we simply decrease the connection counter as there are more than one active connection. `SimpleCollection.disconnectSynchronized` now waits until forever in the while loop as the disconnect isn't called again but obviously there is still a active connection which results in Cryptomator does not fully start up but hangs in the `VaultDetailLockedController` constructor in the `keychain.isLocked()` call.

**Comment by swiesend** [comment]
Yes, the `while` loop was quite optimistic there. I am sorry you had to debug this, without any clue!

The give both an own connection seems like a good solution, but comes with some overhead.

Maybe I just try to `close` the connection for specific amount of time or several attempts and log that if it fails.

Do you have a @SailReal better suggestion?

**Comment by purejava** [comment]
To be honest, when I started development with D-Bus, all documentation stated to open a connection to D-Bus with / by using `DBusConnection getConnection`. This seems to be the right way. Looking at the code of D-Bus now shows me, that this is using an existing connection while opening a new session. The latter was always clear to me. I understood for the first time that `getConnection` indeed reuses an existing connection, when I read https://github.com/cryptomator/cryptomator/issues/1815#issuecomment-929399558 and took a closer look at the D-Bus code afterwards.

Using an own connection comes with some overhead, @swiesend is right, but I am unsure, what's best here. Probably closing a connection after it's not required any more.
