### ISSUE TITLE
Modularize secret-service library

### ISSUE THREAD

**Issue by infeo** [cryptomator/integrations-linux#26]
Since merge of https://github.com/cryptomator/integrations-linux/pull/18, this project is modularized. All dependencies except one are named modules.

The odd one out is `de.swiesend:secret-service`. There are attempts to modularize it (see https://github.com/swiesend/secret-service/pull/40), but until then this dependency is included as an [automatic module](https://openjdk.org/projects/jigsaw/spec/sotms/#automatic-modules). Since there is no encapsulation in an automatic module, all packages (internal or not) are exposed. This can cause split packages.

We should work towards a solution (fixing or forking upstream) to avoid this trap.

**Comment by overheadhunter** [comment]
> Since there is no encapsulation in an automatic module, all packages (internal or not) are exposed. This can cause split packages.

Afaik this is regardless of visibility.

Maybe we should just fork it temporarily.

**Comment by swiesend** [comment]
I take time tomorrow to solve this: https://github.com/swiesend/secret-service/issues/7 but I won't find time to write the https://github.com/cryptomator/integrations-linux part.

**Comment by overheadhunter** [comment]
No worries, nothing to do in this lib on your part. We don't necessarily need https://github.com/swiesend/secret-service/issues/7. This would of course be a nice improvement, but is not blocking us from anything.
