### ISSUE TITLE
Remove Workaround code "catch RuntimeException | ExceptionInInitializerError "

### ISSUE THREAD

**Issue by infeo** [cryptomator/integrations-linux#5]
With 3dfbc3f PR #4 was merged to prevent application crash on systems without a session DBus. But it is only a workaround, because either a very generic `RuntimeException` or an `ExceptionInInitializeError` is catched.

This code should be removed as soon as possible by updating upstream libraries.

**Comment by infeo** [comment]
A new version of dbus-java is out which would make this worarkound code obsolete. @swiesend , @purejava Can you check secret-service/kdewallet can be updatet to use the new release? Also PR #9 would benefit from this change.

**Comment by purejava** [comment]
kdewallet could be updated to dbus-java 3.3.0 without problems. kdewallet 1.2.1 depends on dbus-java 3.3.0 and is still backwards compatible for the Cryptomator implementation [as the current keychain interface is not designed for async usage](https://github.com/cryptomator/integrations-linux/pull/3#pullrequestreview-548388485).
